### PR TITLE
create space between PaddedIcons

### PR DESCRIPTION
**Pull request by shivarm**
image

### CODE REVIEW

**Comment by holly-cummins** [comment]
I agree that this looks better, but it's less consistent with the footer on https://quarkus.io, which also has the closely-spaced icons. 

image

I've just tried to find other places where the creative commons icons are used, and it seems like they're often snuggled together (I think this is a wikipedia screencap, but it was via flickr):

image

**Comment by shivarm** [comment]
> I agree that this looks better, but it's less consistent with the footer on https://quarkus.io, which also has the closely-spaced icons.

This is why I have change, snuggled not look cool as compare to current
> 
> image
> I've just tried to find other places where the creative commons icons are used, and it seems like they're often snuggled together (I think this is a wikipedia screencap, but it was via flickr):
> 
> image

**Comment by shivarm** [comment]
Is there is any Convention? so will close this PR.

**Comment by shivam-sharma7** [comment]
@gsmet WDYT?

**Comment by gastaldi** [comment]
+1 to keep the same layout as in quarkus.io. Closing this PR now, thanks

**Pull request closed without merging**
